$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline                      # ← overall job type
name: used_car_price_pipeline
description: Preprocess → train → register pipeline for used-car price model

######################
# pipeline-level inputs
######################
inputs:
  input_csv:        # raw CSV file you uploaded as a data asset
    type: uri_file
  test_train_ratio: 0.2
  n_estimators:     50
  max_depth:        5

#####################################
# step 1 – data-prep command component
#####################################
jobs:
  prep:
    type: command
    component: azureml:dataprep_component:1      # version 1 registered earlier
    inputs:
      data:             ${{parent.inputs.input_csv}}
      test_train_ratio: ${{parent.inputs.test_train_ratio}}

##########################################
# step 2 – training command component
##########################################
  train:
    type: command
    component: azureml:train_component:1
    inputs:
      train_data:  ${{parent.jobs.prep.outputs.train_data}}
      test_data:   ${{parent.jobs.prep.outputs.test_data}}
      n_estimators: ${{parent.inputs.n_estimators}}
      max_depth:    ${{parent.inputs.max_depth}}

##########################################
# step 3 – model-register command component
##########################################
  register:
    type: command
    component: azureml:register_component:1
    inputs:
      model: ${{parent.jobs.train.outputs.model_output}}
