$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
name: used_car_price_pipeline
description: End-to-end data prep → train → register
compute: azureml:cpu-cluster        # pipeline-level default

# -------- top-level pipeline inputs --------
inputs:
  input_csv:        {type: uri_file}
  test_train_ratio: {type: number,  default: 0.2}
  n_estimators:     {type: integer, default: 50}
  max_depth:        {type: integer, default: 5}

# -------- jobs (three command components) --------
jobs:

  prep:
    type: component
    component: azureml:dataprep_component:1
    compute:  azureml:cpu-cluster
    inputs:
      data:             ${{parent.inputs.input_csv}}
      test_train_ratio: ${{parent.inputs.test_train_ratio}}

  train:
    type: component
    component: azureml:train_component:1
    compute:  azureml:cpu-cluster
    inputs:
      train_data:  ${{parent.jobs.prep.outputs.train_data}}
      test_data:   ${{parent.jobs.prep.outputs.test_data}}
      n_estimators:${{parent.inputs.n_estimators}}
      max_depth:   ${{parent.inputs.max_depth}}

  register:
    type: component
    component: azureml:register_component:1
    compute:  azureml:cpu-cluster
    inputs:
      model: ${{parent.jobs.train.outputs.model_output}}
