$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

# -------------- pipeline-level data input only --------------
inputs:
  input_csv:                # the CSV you registered
    type: uri_file

# default compute for every step (optional)
compute: azureml:cpu-cluster

# -------------- jobs ------------------
jobs:
  # 1 ────────────── data-prep ─────────────
  prep:
    type: command
    component: azureml:dataprep_component:1
    inputs:
      data:            ${{parent.inputs.input_csv}}
      test_train_ratio: 0.2                     # ← primitive passed here
    outputs:                                    # let Azure choose the path
      train_data: ${{parent.outputs.train}}
      test_data:  ${{parent.outputs.test}}

  # 2 ────────────── train model ────────────
  train:
    type: command
    component: azureml:train_component:1
    inputs:
      train_data:  ${{parent.jobs.prep.outputs.train_data}}
      test_data:   ${{parent.jobs.prep.outputs.test_data}}
      n_estimators: 50
      max_depth:     5
    outputs:
      model_output: ${{parent.outputs.trained_model}}

  # 3 ────────────── register ──────────────
  register:
    type: command
    component: azureml:register_component:1
    inputs:
      model: ${{parent.jobs.train.outputs.model_output}}
