# ========= pipeline_job.yml =========
$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

# ---------- top-level inputs (pipeline parameters) ----------
inputs:
  input_csv:
    type: uri_file
  test_train_ratio:
    type: number
    default: 0.2
  n_estimators:
    type: integer
    default: 50
  max_depth:
    type: integer
    default: 5

# ---------- compute to reuse ----------
compute: azureml:cpu-cluster   # default for any step that omits "compute:"

# ---------- jobs (three command components) ----------
jobs:
  # 1 Data-prep step
  prep:
    type: command
    component: azureml:dataprep_component:1
    compute: azureml:cpu-cluster          # explicit or let it inherit
    inputs:
      data:             ${{parent.inputs.input_csv}}
      test_train_ratio: ${{parent.inputs.test_train_ratio}}
    outputs:
      train_data:       ${{parent.outputs.prep_train}}   # let Azure ML choose path
      test_data:        ${{parent.outputs.prep_test}}

  # 2 Training step
  train:
    type: command
    component: azureml:train_component:1
    compute: azureml:cpu-cluster
    inputs:
      train_data:   ${{parent.jobs.prep.outputs.train_data}}
      test_data:    ${{parent.jobs.prep.outputs.test_data}}
      n_estimators: ${{parent.inputs.n_estimators}}
      max_depth:    ${{parent.inputs.max_depth}}
    outputs:
      model_output: ${{parent.outputs.rf_model}}

  # 3 Register step
  register:
    type: command
    component: azureml:register_component:1
    compute: azureml:cpu-cluster
    inputs:
      model: ${{parent.jobs.train.outputs.model_output}}

# ---------- outputs you want surfaced----------
outputs:
  trained_model: ${{jobs.train.outputs.model_output}}
