name: Azure ML CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Register components
      run: |
        for comp in .azureml/dataprep_component.yml .azureml/train_component.yml .azureml/register_component.yml
        do
          az ml component create \
            --file $comp \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --workspace-name ${{ secrets.AZURE_ML_WORKSPACE }}
        done

    - name: Run pipeline (prep -> train -> register)
      run: |
        az ml job create \
          --file .azureml/pipeline_job.yml \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --workspace-name ${{ secrets.AZURE_ML_WORKSPACE }} \
          --set inputs.input_csv=${{ secrets.INPUT_CSV_PATH }} \
          --name ci_pipeline_run \
          --stream
